#!/bin/bash

printf "\nSiFi Start\n"


printf "Give path:"
read path
printf "What you want to do write \n 1-Move to new Directory \n 2-Remove files \n 3-move to existant directory\n 4-Exit \nGive:"
read status

while [ $status -eq "1" ] || [ $status -eq "2" ] || [ $status -eq "3" ] || [ $status -eq "3" ]
do
# Move to new Directory
if [ $status -eq 1 ]
then

  echo "Give file type:"
  read filetype


  ls $path | egrep *$filetype

  echo "give name directory to create:"
  read namedir

  mkdir $path/$namedir ; mv $path/*$filetype $path/$namedir

  ls $path/$namedir

# Remove Files

elif [ $status -eq 2 ]
then
  printf "Give type file you wan to Remove:"
  read filetype
  rm $path/*$filetype
  echo
  ls $path
# Move to Existant directory
elif [ perpose -eq 3 ]
then
  printf "Give type Path you wan to Move:"
  read filetype
  printf "Give file type you wan to move:"
  read path2

  mv $path/*$filetype $path2

  ls $path2

else
  echo End SiFi
  
fi
printf "What you want to do write \n 1-Move to new Directory \n 2-Remove files \n 3-move to existant directory\n Give:"
read status
done
echo "End SiFi"


